### ISSUE TITLE
Active IntelliSense row has the same font and background color

### ISSUE THREAD

**Issue by dishmint** [wxlfe/gold-standard-vscode#1]
Hi,
I'm really enjoying the light variant! However, the active row in IntelliSense has the same font and background color. afaict this is the only place it happens.

<img width="826" alt="Screenshot 2023-11-16 at 10 58 00 PM" src="https://github.com/wxlfe/gold-standard-vscode/assets/18143853/3d9e411b-1d95-456a-b535-fd8d4d107e77">

Maybe the same styling as the command palette would work, or a lighter background color?

<img width="601" alt="Screenshot 2023-11-16 at 11 08 29 PM" src="https://github.com/wxlfe/gold-standard-vscode/assets/18143853/f98277af-477f-4654-8455-9496252dae07">

Thanks for the great theme!

**Comment by wxlfe** [comment]
@dishmint Thanks for the kind words and the super helpful suggestion! Should look a lot better now!

**Comment by dishmint** [comment]
Looks great! 🙏
